{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n +  where 4 = func(3)", "trace": "def test_answer():\n>       assert func(3)==5\nE       assert 4 == 5\nE        +  where 4 = func(3)\n\ntest_demo.py:5: AssertionError"}, "start": 1603265928406, "stop": 1603265928406, "uuid": "62940fae-a319-481a-ac4f-36207853f0ab", "historyId": "8eb971d13b0d6a43fe517151dead2e2a", "testCaseId": "f09542d7d0cd3629beb2fa5024c22587", "fullName": "test_demo#test_answer", "labels": [{"name": "suite", "value": "test_demo"}, {"name": "host", "value": "tonghui"}, {"name": "thread", "value": "19792-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_demo"}]}